services:
  anythingllm:
    image: mintplexlabs/anythingllm:latest@sha256:c9dcfee8d9504a63afadb735e8ea9780b5ecb2da4d0dfeb1af5450d91ed1af03
    ports:
      - "3001:3001"
    environment:
      - STORAGE_DIR=/app/server/storage
    volumes:
      - anythingllm_data:/app/server/storage

volumes:
  anythingllm_data:
